import os

FIELD_SEARCH_MAX_WORKERS = int(os.getenv("FIELD_SEARCH_MAX_WORKERS", "4"))
FIELD_SEARCH_COLUMN_BATCH = int(os.getenv("FIELD_SEARCH_COLUMN_BATCH", "100"))
FIELD_SEARCH_VALUE_MATCH_MAX_TABLES = int(os.getenv("FIELD_SEARCH_VALUE_MATCH_MAX_TABLES", "200"))
FIELD_SEARCH_VALUE_MATCH_MAX_COLUMNS = int(os.getenv("FIELD_SEARCH_VALUE_MATCH_MAX_COLUMNS", "500"))
FIELD_SEARCH_BG_JOB_TTL = int(os.getenv("FIELD_SEARCH_BG_JOB_TTL", "1800"))
